src/main/java/fr/cgi/magneto/Magneto.java, src/main/java/fr/cgi/magneto/controller/BoardController.java, src/main/java/fr/cgi/magneto/controller/MagnetoController.java, src/main/java/fr/cgi/magneto/core/constants/Collections.java, src/main/java/fr/cgi/magneto/core/constants/Field.java, src/main/java/fr/cgi/magneto/core/constants/Rights.java, src/main/java/fr/cgi/magneto/helper/DateHelper.java, src/main/java/fr/cgi/magneto/helper/WorkflowHelper.java, src/main/java/fr/cgi/magneto/model/Board.java, src/main/java/fr/cgi/magneto/model/Model.java, src/main/java/fr/cgi/magneto/model/MongoQuery.java, src/main/java/fr/cgi/magneto/security/ViewRight.java, src/main/java/fr/cgi/magneto/service/BoardService.java, src/main/java/fr/cgi/magneto/service/ServiceFactory.java, src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java, src/main/resources/jsonschema/board.json, src/test/java/fr/cgi/magneto/model/BoardTest.java, src/test/java/fr/cgi/magneto/model/MongoQueryTest.java, src/test/java/fr/cgi/magneto/service/BoardServiceTest.java
- Added 2 API endpoints for creating a board and fetching all boards
- check if both APIs are behaving properly with the expected parameters (see : https://confluence.support-ent.fr/display/RN/Boards)
https://jira.support-ent.fr/browse/MAG-5
https://jira.support-ent.fr/browse/MAG-6
=> feat(boards): #MAG-5/6 (back) display+create all boards

src/main/java/fr/cgi/magneto/controller/BoardController.java, src/main/java/fr/cgi/magneto/model/FolderPayload.java, src/main/java/fr/cgi/magneto/service/BoardService.java, src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/jsonschema/moveBoards.json, src/main/resources/public/template/boards.html, src/main/resources/public/ts/controllers/__test__/boards.controller.test.ts, src/main/resources/public/ts/controllers/boards.controller.ts, src/main/resources/public/ts/directives/board-move-lightbox/board-move-lightbox.directive.ts, src/main/resources/public/ts/directives/board-move-lightbox/board-move-lightbox.html, src/main/resources/public/ts/directives/index.ts, src/main/resources/public/ts/directives/toaster/toaster.directive.ts, src/main/resources/public/ts/directives/toaster/toaster.html, src/main/resources/public/ts/services/__test__/boards.service.test.ts, src/main/resources/public/ts/services/boards.service.ts
- add popup to move a board to a folder
- check if a board is correctly moved after validation
https://jira.support-ent.fr/browse/MAG-26
=> feat(boards/folders): #MAG-26 move boards to a folder

build.gradle, deployment/magneto/conf.json.template, package.json, src/main/java/fr/cgi/magneto/Magneto.java, src/main/java/fr/cgi/magneto/config/MagnetoConfig.java, src/main/java/fr/cgi/magneto/controller/MagnetoController.java, src/main/java/fr/cgi/magneto/core/constants/Field.java, src/main/java/fr/cgi/magneto/realtime/Collaboration.java, src/main/java/fr/cgi/magneto/realtime/CollaborationApiController.java, src/main/java/fr/cgi/magneto/realtime/CollaborationRepostiory.java, src/main/java/fr/cgi/magneto/realtime/RealTimeCollaboration.java, src/main/java/fr/cgi/magneto/realtime/RealTimeController.java, src/main/java/fr/cgi/magneto/service/ServiceFactory.java, src/main/resources/public/template/boards.html, src/main/resources/public/ts/controllers/board-view.controller.ts, src/main/resources/public/ts/controllers/main.ts, src/main/resources/public/ts/directives/index.ts, src/main/resources/public/ts/directives/websocket-test/card-notify/card-notify.directive.html, src/main/resources/public/ts/directives/websocket-test/card-notify/card-notify.directive.ts, src/main/resources/public/ts/directives/websocket-test/card-profile.directive.html, src/main/resources/public/ts/directives/websocket-test/card-profile.directive.ts, src/main/resources/public/ts/shared/event-bus-service/event-bus-sockjs.service.ts, src/main/resources/view-src/magneto.html
Mise en place des outils et implémentations pour faire fonctionner les websockets.
On utilise SockJS qui est une bibliothèque JavaScript pour navigateur qui fournit un objet de type WebSocket. SockJS offre une API Javascript cross-browser qui crée une commmunication cross-domain entre le navigateur et Vert.x.
On arrive à utiliser les websocket côté appli mobile (cf commit : https://github.com/opendigitaleducation/ode-mobile-framework/commit/e26241aa272dd1fa926a9d039364b71d0ba5a262).
Les dépendances qui ont été rajouté côté front : 
- sockjs-client: 1.6.1
- @types/sockjs-client: 1.5.1
côté gradle : 
- vertx-sockjs-service-proxy
- vertx-service-proxy
Pour tester dans un environnement de recette, il faudra positionner dans la configuration de nginx : 
```
location /magneto/eventbus { …
```
=> feat(websocket): add websocket tools for implementation

src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/sass/global/components/_icons.scss, src/main/resources/public/sass/global/components/containers/_board.scss, src/main/resources/public/sass/global/components/directives/_board-nav.scss, src/main/resources/public/sass/global/components/directives/_card-list.scss, src/main/resources/public/sass/global/components/directives/_index.scss, src/main/resources/public/template/board.html, src/main/resources/public/ts/controllers/board-view.controller.ts, src/main/resources/public/ts/controllers/boards.controller.ts, src/main/resources/public/ts/directives/board-nav/board-nav.directive.ts, src/main/resources/public/ts/directives/board-nav/board-nav.html, src/main/resources/public/ts/directives/card-manage-lightbox/card-manage-lightbox.html, src/main/resources/public/ts/directives/index.ts, src/main/resources/public/ts/directives/linker/linker.directive.ts, src/main/resources/public/ts/directives/linker/linker.html, src/main/resources/public/ts/directives/media-library-lightbox/media-library-lightbox.directive.ts, src/main/resources/public/ts/directives/media-library-lightbox/media-library-lightbox.html, src/main/resources/public/ts/models/__test__/board.model.test.ts, src/main/resources/public/ts/models/board.model.ts
- add side-bar for adding different types of magnets
- check if magnet creation is working properly for all types
https://jira.support-ent.fr/browse/MAG-8
=> feat(cards): #MAG-8 add side-bar for creating cards

src/main/resources/public/img/extension/default.svg, src/main/resources/public/img/extension/link.svg, src/main/resources/public/sass/global/components/containers/_board.scss, src/main/resources/public/sass/global/components/directives/_card-list-item.scss, src/main/resources/public/sass/global/components/directives/_card-manage-lightbox.scss, src/main/resources/public/template/board.html, src/main/resources/public/ts/core/enums/resource-type.enum.ts, src/main/resources/public/ts/directives/card-list/card-list-item-preview.directive.ts, src/main/resources/public/ts/directives/card-list/card-list-item-preview.html, src/main/resources/public/ts/directives/card-list/card-list-item.html
Visual changes for cards
- New default icon and link
- Responsive fix
- New card display
https://jira.support-ent.fr/browse/MAG-59
=> fix(cards): #MAG-59 fix visual for board view

src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java, src/main/resources/public/ts/controllers/boards.controller.ts, src/main/resources/public/ts/directives/board-manage-lightbox/board-manage-lightbox.directive.ts, src/main/resources/public/ts/directives/toaster/toaster.html
- open board after its creation
- check if the board is opened properly after its creation
- check if board update/delete is still working normally
https://jira.support-ent.fr/browse/MAG-60
=> fix(boards): #MAG-60 open board on creation

src/main/resources/public/sass/global/components/containers/_boards.scss, src/main/resources/public/sass/global/components/directives/_board-list-folder.scss, src/main/resources/public/template/boards.html, src/main/resources/public/ts/controllers/board-view.controller.ts, src/main/resources/public/ts/controllers/boards.controller.ts, src/main/resources/public/ts/models/folder-tree.model.ts
- added update folders on search
- updated folder button size
- fixed toasts displaying behind the boards view header
- fixed folder tree update on folder rename
- on board page load, scroll to the top of the page
- check if search il filtering folders and boards
- check if the main view is displayed properly
- check if message toasts are displaying properly
- check if folder names are updated in folder tree after renaming
https://jira.support-ent.fr/browse/MAG-64
https://jira.support-ent.fr/browse/MAG-73
https://jira.support-ent.fr/browse/MAG-72
https://jira.support-ent.fr/browse/MAG-70
https://jira.support-ent.fr/browse/MAG-61
=> fix(folders + scss): add folder search + display fixes

src/main/java/fr/cgi/magneto/core/constants/Mongo.java, src/main/java/fr/cgi/magneto/service/ServiceFactory.java, src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java, src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java, src/main/resources/public/sass/global/components/containers/_boards.scss, src/main/resources/public/template/board.html, src/main/resources/public/ts/controllers/board-view.controller.ts
- adapt create folder button for small width screens
- fix media-library display after opening the sound popup
- fix board deletion on folder delete
- fix board display in trash
- test if boards displayed in trash are deleted and matching their parent boards
- test if the add image popup is displayed properly after having opened the sound popup beforehand
https://jira.support-ent.fr/browse/MAG-6
https://jira.support-ent.fr/browse/MAG-68
https://jira.support-ent.fr/browse/MAG-26
=> fix(folders/media-library): display + delete folder fixes 

src/main/resources/public/template/board.html, src/main/resources/public/ts/controllers/board-view.controller.ts, src/main/resources/public/ts/directives/card-list/card-list.directive.ts
- on card drag and drop and card creation : fetch new board modification date
- check if board modification date is updating on drag and drop of cards
- check if board modification date is updating on card creation
https://jira.support-ent.fr/browse/MAG-69
=> fix(board): #MAG-69 update save date on magnet move/creation

src/main/java/fr/cgi/magneto/model/boards/Board.java, src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java, src/main/resources/public/ts/directives/board-keywords-input/board-keywords-input.directive.ts, src/test/java/fr/cgi/magneto/model/BoardTest.java
- fixed diaplay of board tags in property popup (opened from board view)
- fixed tags submit text
- check if board tags are properly displayed in the properties popup
- check if adding tags to a board is applied properly 
https://jira.support-ent.fr/browse/MAG-75
=> fix(board-tags): #MAG-75 display tags in board view + fix tag input

src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/sass/global/_mixins.scss, src/main/resources/public/sass/global/components/_lightbox.scss, src/main/resources/public/sass/global/components/containers/_boards.scss, src/main/resources/public/sass/global/components/directives/_board-list-item.scss, src/main/resources/public/sass/global/components/directives/_board-nav.scss, src/main/resources/public/sass/global/components/directives/_card-manage-lightbox.scss, src/main/resources/public/sass/global/components/directives/_folder-tree-nav.scss, src/main/resources/public/sass/global/components/directives/_search-bar.scss, src/main/resources/public/template/boards.html, src/main/resources/public/ts/controllers/boards.controller.ts, src/main/resources/public/ts/directives/folder-tree-nav/folder-tree-nav-item/folder-tree-nav-item.html
- adapt boards list display for mobile
- check if board list is displayed properly on desktop and mobile
https://jira.support-ent.fr/browse/MAG-71
=> fix(boards-mobile): #MAG-71 adapt boards view for mobile screens

src/main/resources/public/ts/controllers/board-read.controller.ts, src/main/resources/public/ts/controllers/board-view.controller.ts, src/main/resources/public/ts/controllers/boards.controller.ts, src/main/resources/public/ts/models/__test__/cards-filter.model.test.ts, src/test/java/fr/cgi/magneto/model/MetadataTest.java
- add missing unit tests for models
- add missings comments on front controllers 
- check that unit tests do not fail
https://jira.support-ent.fr/browse/MAG-76
=> feat(tests+comm): add unit tests + comments in controllers

src/main/resources/public/template/board.html, src/main/resources/public/ts/directives/card-list/card-list.directive.ts
- prevent drag and drop of cards for users who are not allowed
- check if users can or cannot drag and drop cards based on their rights
https://jira.support-ent.fr/browse/MAG-14
=> fix(cards): #MAG-14 prevent drag and drop if user user has no right

src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java, src/test/java/fr/cgi/magneto/service/BoardServiceTest.java
- allow user to search boards regardless of its parent folder
- check if user can search boards in all folders
https://jira.support-ent.fr/browse/MAG-70
=> fix(search): #MAG-70 remove folder filter when searching a board

src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java, src/main/resources/public/template/board.html
- removed sidebar in shared board if user has no writing right
- removed read-only boards from shared cards collection results on search
- removed "Reading" button if board has no cards.
- check if results in shared collection are matching the user rights
- check if the reading button is displayed or not related to the number of cards
- check if the user has not access to the sidebar in a shared board if they have the reuse right
https://jira.support-ent.fr/browse/MAG-16
=> fix(share): #MAG-16 remove read-only boards from shared card collection results + sidebar removed on reuse right

src/main/java/fr/cgi/magneto/controller/BoardController.java, src/main/java/fr/cgi/magneto/controller/CardController.java, src/main/java/fr/cgi/magneto/core/constants/Actions.java
- add @Trace to API routes
- check if apis are behaving as usual + check if traces are inserted in mongo DB
https://jira.support-ent.fr/browse/MAG-82
=> feat(traces): #MAG-82 add traces to API routes

LICENCE, README.md, src/main/java/fr/cgi/magneto/controller/BoardController.java, src/main/java/fr/cgi/magneto/controller/CardController.java, src/main/java/fr/cgi/magneto/controller/MagnetoController.java, src/main/java/fr/cgi/magneto/core/enums/Events.java
- add README
- add LICENCE
- add Event store
https://jira.support-ent.fr/browse/MAG-87
=> chore: #MAG-87 add readme/licence + eventStore

src/main/resources/i18n/de.json, src/main/resources/i18n/en.json, src/main/resources/i18n/es.json, src/main/resources/i18n/fr.json, src/main/resources/i18n/it.json, src/main/resources/i18n/pt.json, src/main/resources/public/ts/controllers/board-view.controller.ts, src/main/resources/public/ts/directives/linker/linker.directive.ts, src/main/resources/public/ts/directives/linker/linker.html, src/main/resources/public/ts/models/card.model.ts, src/main/resources/public/ts/models/index.ts, src/main/resources/public/ts/models/linker.model.ts, src/main/resources/public/ts/services/linker.service.ts
- allow user to add a link to other application as a card
- allow user to add a link to a website as a card
- check if external linker card creation is working
- check if internal linker card creation is working
https://jira.support-ent.fr/browse/MAG-58
=> feat(cards): #MAG-58 add linker directive

src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java, src/main/resources/public/template/boards.html, src/main/resources/public/ts/controllers/boards.controller.ts, src/main/resources/public/ts/directives/board-list/board-list.directive.ts, src/main/resources/public/ts/directives/board-list/board-list.html, src/main/resources/public/ts/directives/folder-tree-nav/folder-tree-nav-item/folder-tree-nav-item.directive.ts, src/main/resources/public/ts/directives/folder-tree-nav/folder-tree-nav.directive.ts, src/main/resources/public/ts/directives/folder-tree-nav/folder-tree-nav.html, src/main/resources/public/ts/models/__test__/board.model.test.ts, src/main/resources/public/ts/models/board.model.ts, src/main/resources/public/ts/models/draggable.model.ts
- add drag and drop from boards to folders/folders tree
- check if we can move one board to another folder
- check if we can select several boards to another folder
- check if we can move boards to trash folder to delete
- check if we cannot move board to an other folder in trash/public folder
- check if we cannot move board to the same folder
https://jira.support-ent.fr/browse/MAG-83
=> feat(boards): #MAG-83 add drag and drop boards/folders

src/main/java/fr/cgi/magneto/controller/BoardController.java, src/main/java/fr/cgi/magneto/controller/CardController.java, src/main/java/fr/cgi/magneto/security/DuplicateRight.java, src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java, src/main/resources/public/template/boards.html, src/main/resources/public/ts/behaviours.ts, src/main/resources/public/ts/controllers/boards.controller.ts, src/main/resources/public/ts/controllers/main.ts, src/main/resources/public/ts/magnetoBehaviours.ts, src/main/resources/public/ts/utils/rights.utils.ts
- add workflow publish condition to hide it in toaster when not available
- check if we can see the share/unshare to public button in toaster without publish workflow right
https://jira.support-ent.fr/browse/MAG-93
=> fix(sharing): #MAG-93 add publish workflow condition

src/main/java/fr/cgi/magneto/controller/CardController.java
- use generated id to create a card and avoid get last document in mongodb problem when inserting to boards.
- check if we can create a card in production
https://jira.support-ent.fr/browse/MAG-96
=> fix(card): #MAG-96 fix card creation

src/main/resources/public/sass/global/components/containers/_boards.scss, src/main/resources/public/sass/global/components/directives/_board-list-folder.scss, src/main/resources/public/sass/global/components/directives/_search-bar.scss
Changes blue to ent color for search bar, folder icon and create folder button (primary)
Check if color change according to the theme selected
https://jira.support-ent.fr/browse/MAG-92
=> fix(colors): #MAG-91 fix colors according to ent themes

src/main/java/fr/cgi/magneto/controller/BoardController.java, src/main/java/fr/cgi/magneto/controller/CardController.java, src/main/java/fr/cgi/magneto/security/DuplicateBoardRight.java, src/main/java/fr/cgi/magneto/security/DuplicateCardRight.java
Rights weren't correctly set. We cannot access ton the api point. It's a fix for the PR below :
https://github.com/CGI-OPEN-ENT-NG/magneto/pull/36
Check if we can duplicate a board.
https://jira.support-ent.fr/browse/MAG-17
https://jira.support-ent.fr/browse/MAG-98
=> fix(boards): #MAG-17 fix duplicate boards rights

src/main/resources/public/ts/directives/card-list/card-list-item-options.html, src/main/resources/public/ts/directives/toaster/toaster.html
Fix orders of actions buttons for cards and boards
Check if the order is good according to the ticket
https://jira.support-ent.fr/browse/MAG-100
=> fix(toaster): #MAG-100 fix order of button in options

src/main/resources/public/ts/directives/card-list/card-list.html
- add preview dbl click
- check if the user have reader right he can preview by dbl click, if he has writer rights, he can edit by dbl click.
https://jira.support-ent.fr/browse/MAG-88
=> feat(cards): #MAG-88 add preview dbl click event when no more rights

src/main/java/fr/cgi/magneto/service/CardService.java, src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java, src/main/resources/public/ts/services/linker.service.ts
- fix linker directive due to 4.6 entcore upgrade
- remove user id check in update/delete cards to avoid problems while sharing
- check if apps are available in linker
- check if edit/delete are available when a user sahred to you a board
https://jira.support-ent.fr/browse/MAG-58
https://jira.support-ent.fr/browse/MAG-16
=> fix(cards): #MAG-58 fix linker directive + sharing rights

src/main/resources/public/template/board-read.html, src/main/resources/public/template/board.html, src/main/resources/public/ts/directives/card-collection/card-collection.html, src/main/resources/public/ts/directives/card-list/card-list-item.html, src/main/resources/public/ts/directives/card-list/card-list.directive.ts, src/main/resources/public/ts/directives/card-preview-lightbox/card-preview-lightbox.directive.ts, src/main/resources/public/ts/directives/card-preview-lightbox/card-preview-lightbox.html, src/main/resources/public/ts/directives/section-list/section-list-item.directive.ts, src/main/resources/public/ts/directives/section-list/section-list-item.html, src/main/resources/public/ts/directives/section-list/section-list.directive.ts, src/main/resources/public/ts/directives/section-list/section-list.html, src/main/resources/public/ts/models/board.model.ts, src/main/resources/public/ts/models/card.model.ts
- change card elements sizes
- add comment panel in preview mode
- check if all cards are the same size when comments are disabled
- check that comments are displayed properly
https://jira.support-ent.fr/browse/MAG-166
=> fix(cards): #MAG-166 change element sizes + fix display issues
